/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LlmExplainerRouteImport } from './routes/llm-explainer'
import { Route as IndexRouteImport } from './routes/index'

const LlmExplainerRoute = LlmExplainerRouteImport.update({
  id: '/llm-explainer',
  path: '/llm-explainer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/llm-explainer': typeof LlmExplainerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/llm-explainer': typeof LlmExplainerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/llm-explainer': typeof LlmExplainerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/llm-explainer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/llm-explainer'
  id: '__root__' | '/' | '/llm-explainer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LlmExplainerRoute: typeof LlmExplainerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/llm-explainer': {
      id: '/llm-explainer'
      path: '/llm-explainer'
      fullPath: '/llm-explainer'
      preLoaderRoute: typeof LlmExplainerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LlmExplainerRoute: LlmExplainerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
